# Setup Bend Action
#   @author: hustcer
#   @created: 2024/06/09 20:50:20
# REF:
#   - https://docs.github.com/cn/actions/creating-actions/about-custom-actions
#   - https://docs.github.com/cn/actions/creating-actions/metadata-syntax-for-github-actions
#   - https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
#   - https://github.com/actions/runner-images

name: 'Setup Bend'
author: 'hustcer'
description: 'A github action to setup Bend environment'

branding:
  icon: 'code'
  color: 'purple'

inputs:
  action:
    required: false
    default: 'nothing'
    description: 'Just a Test input, no input required currently...'

runs:
  using: 'composite'
  steps:
    - name: Setup Nu
      uses: hustcer/setup-nu@v3
      with:
        version: '0.95.0'

    - name: Get Cache Suffix
      id: cache-suffix
      shell: nu {0}
      run: |
        use ${{ github.action_path }}/nu/bend.nu *
        gen-cache-key

    - uses: actions/cache@v4
      id: cache
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin/hvm*
          ~/.cargo/bin/bend*
        key: ${{ runner.os }}-check-${{ steps.cache-suffix.outputs.suffix }}

    - name: Setup Bend
      shell: nu {0}
      run: |
        use ${{ github.action_path }}/nu/bend.nu *
        setup bend ${{steps.cache.outputs.cache-hit}}

