# Description:
#   - Setup Bend with GitHub Actions
# REF:
#   - https://github.com/marketplace/actions/checkout

name: Setup-Bend@Dev
on:
  push:
    branches:
      - develop

    paths-ignore:
      - '**.md'

jobs:
  setup-bend:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Setup Bend@${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Setup Bend
        uses: hustcer/setup-bend@develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check bend Version
        run: |
          bend --version
          bend run examples/sequential_sum.bend -s
          bend run-c examples/sequential_sum.bend -s
          bend run-cu examples/sequential_sum.bend -s

