# Description:
#   - Setup Bend with GitHub Actions
# REF:
#   - https://github.com/marketplace/actions/checkout

name: Setup-Bend@Dev
on:
  push:
    branches:
      - develop

    paths-ignore:
      - '**.md'

jobs:
  setup-bend:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Setup Bend@${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Setup Bend
        uses: hustcer/setup-bend@develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check bend Version
        run: bend --version

      - name: Sum using Rust interpreter (Sequential)
        shell: nu {0}
        run: |
          print $'Rust version: (ansi g)(rustc --version)(ansi reset)'
          bend run examples/sequential_sum.bend -s

      - name: Sum using C interpreter (Sequential)
        shell: nu {0}
        if: matrix.os != 'windows-latest'
        run: |
          print $'Gcc version: (ansi g)(gcc --version)(ansi reset)'
          bend run-c examples/sequential_sum.bend -s

