# Description:
#   - Add milestone to a merged PR or closed issue.

name: Milestone Action
on:
  issues:
    types: [closed]
  pull_request_target:
    types: [closed]

# Fix GraphQL: Resource not accessible by integration (updatePullRequest)
permissions:
  contents: write
  pull-requests: write

jobs:
  update-milestone:
    runs-on: ubuntu-latest
    name: Milestone Update
    steps:
      - name: Set Milestone for PR
        uses: hustcer/milestone-action@main
        if: github.event.pull_request.merged == true
        with:
          action: bind-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Milestone for Issue
        uses: hustcer/milestone-action@main
        if: github.event.issue.state == 'closed'
        with:
          action: bind-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
